-- ==============================================================================
-- DistriFlow ERP — Supabase PostgreSQL Schema & Row Level Security (RLS) Policies
-- ==============================================================================

-- 1. PROFILES & ROLES
CREATE TYPE user_role AS ENUM ('OWNER', 'SALESPERSON');

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'SALESPERSON',
  phone TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. SUPPLIERS
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT,
  payable_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. PRODUCT CATEGORIES & PRODUCTS
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'pcs',
  purchase_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  selling_price NUMERIC(10, 2) NOT NULL,
  current_stock INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 10,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. RETAILERS / CUSTOMERS
CREATE TABLE IF NOT EXISTS retailers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT NOT NULL,
  city TEXT,
  assigned_salesperson_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  credit_limit NUMERIC(12, 2) NOT NULL DEFAULT 5000.00,
  outstanding_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. ORDERS & ITEMS
CREATE TYPE order_status AS ENUM (
  'DRAFT',
  'SUBMITTED',
  'CHANGES_REQUESTED',
  'APPROVED',
  'REJECTED',
  'INVOICED',
  'DISPATCHED',
  'DELIVERED',
  'CANCELLED'
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  salesperson_id UUID REFERENCES profiles(id) ON DELETE RESTRICT NOT NULL,
  order_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  status order_status NOT NULL DEFAULT 'DRAFT',
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  discount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  notes TEXT,
  owner_feedback TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10, 2) NOT NULL,
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  total NUMERIC(12, 2) NOT NULL
);

-- 6. INVOICES & ITEMS
CREATE TYPE invoice_payment_status AS ENUM ('UNPAID', 'PARTIALLY_PAID', 'PAID');

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT UNIQUE NOT NULL,
  order_id BIGINT REFERENCES orders(id) ON DELETE RESTRICT NOT NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  invoice_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  due_date TIMESTAMPTZ NOT NULL,
  subtotal NUMERIC(12, 2) NOT NULL,
  discount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  tax NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(12, 2) NOT NULL,
  amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  remaining_balance NUMERIC(12, 2) NOT NULL,
  payment_status invoice_payment_status NOT NULL DEFAULT 'UNPAID',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  discount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  total NUMERIC(12, 2) NOT NULL
);

-- 7. PURCHASES & ITEMS
CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_number TEXT UNIQUE NOT NULL,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE RESTRICT NOT NULL,
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  total_amount NUMERIC(12, 2) NOT NULL,
  amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  payment_status invoice_payment_status NOT NULL DEFAULT 'UNPAID',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS purchase_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id BIGINT REFERENCES purchases(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  purchase_price NUMERIC(10, 2) NOT NULL,
  total NUMERIC(12, 2) NOT NULL
);

-- 8. PAYMENTS
CREATE TYPE payment_type AS ENUM ('RETAILER_COLLECTION', 'SUPPLIER_PAYMENT');
CREATE TYPE payment_method AS ENUM ('CASH', 'BANK_TRANSFER', 'CHEQUE', 'MOBILE_MONEY');

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_number TEXT UNIQUE NOT NULL,
  type payment_type NOT NULL,
  entity_id BIGINT NOT NULL, -- retailer_id or supplier_id
  entity_name TEXT NOT NULL,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
  purchase_id BIGINT REFERENCES purchases(id) ON DELETE SET NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  payment_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  payment_method payment_method NOT NULL DEFAULT 'CASH',
  reference_number TEXT,
  notes TEXT,
  recorded_by_user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 9. AUDITABLE INVENTORY MOVEMENTS
CREATE TYPE movement_type AS ENUM (
  'PURCHASE_RECEIPT',
  'ORDER_DELIVERY',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT'
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  movement_type movement_type NOT NULL,
  quantity INT NOT NULL,
  previous_stock INT NOT NULL,
  new_stock INT NOT NULL,
  reference_type TEXT NOT NULL, -- 'ORDER', 'PURCHASE', 'MANUAL_ADJUSTMENT'
  reference_id BIGINT,
  reference_number TEXT,
  reason_or_notes TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 10. DELIVERIES
CREATE TYPE delivery_status AS ENUM ('SCHEDULED', 'DISPATCHED', 'DELIVERED', 'FAILED');

CREATE TABLE IF NOT EXISTS deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  delivery_address TEXT NOT NULL,
  driver_name TEXT,
  driver_phone TEXT,
  status delivery_status NOT NULL DEFAULT 'SCHEDULED',
  scheduled_date TIMESTAMPTZ NOT NULL,
  delivered_date TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE retailers ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;

-- Helper function to check if current user is OWNER
CREATE OR REPLACE FUNCTION is_owner()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'OWNER'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles: Authenticated users can view profiles; only owners can manage
CREATE POLICY "Users can read profiles" ON profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Owners can update profiles" ON profiles FOR ALL TO authenticated USING (is_owner());

-- Products: Everyone authenticated can view; only owners can modify
CREATE POLICY "Read products" ON products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Manage products" ON products FOR ALL TO authenticated USING (is_owner());

-- Retailers: Owners can manage all; Salespersons can view assigned retailers
CREATE POLICY "Retailers select policy" ON retailers FOR SELECT TO authenticated USING (
  is_owner() OR assigned_salesperson_id = auth.uid()
);
CREATE POLICY "Retailers update policy" ON retailers FOR ALL TO authenticated USING (is_owner());

-- Orders: Salespersons can insert/read their own; Owners can manage all
CREATE POLICY "Orders select policy" ON orders FOR SELECT TO authenticated USING (
  is_owner() OR salesperson_id = auth.uid()
);
CREATE POLICY "Salespersons can create orders" ON orders FOR INSERT TO authenticated WITH CHECK (
  salesperson_id = auth.uid()
);
CREATE POLICY "Only owners can approve orders" ON orders FOR UPDATE TO authenticated USING (
  is_owner() OR (salesperson_id = auth.uid() AND status IN ('DRAFT', 'CHANGES_REQUESTED'))
);
