-- ==============================================================================
-- DistriFlow ERP — Supabase PostgreSQL Schema & Row Level Security (RLS) Policies
-- ==============================================================================

-- 1. PROFILES & ROLES
CREATE TYPE user_role AS ENUM ('OWNER', 'SALESPERSON');

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'SALESPERSON',
  phone TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. SUPPLIERS
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT,
  payable_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. PRODUCT CATEGORIES & PRODUCTS
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'pcs',
  purchase_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  selling_price NUMERIC(10, 2) NOT NULL,
  current_stock INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 10,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. RETAILERS / CUSTOMERS
CREATE TABLE IF NOT EXISTS retailers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT NOT NULL,
  city TEXT,
  assigned_salesperson_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  credit_limit NUMERIC(12, 2) NOT NULL DEFAULT 5000.00,
  outstanding_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. ORDERS & ITEMS
CREATE TYPE order_status AS ENUM (
  'DRAFT',
  'SUBMITTED',
  'CHANGES_REQUESTED',
  'APPROVED',
  'REJECTED',
  'INVOICED',
  'DISPATCHED',
  'DELIVERED',
  'CANCELLED'
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  salesperson_id UUID REFERENCES profiles(id) ON DELETE RESTRICT NOT NULL,
  order_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  status order_status NOT NULL DEFAULT 'DRAFT',
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  discount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  notes TEXT,
  owner_feedback TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10, 2) NOT NULL,
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  total NUMERIC(12, 2) NOT NULL
);

-- 6. INVOICES & ITEMS
CREATE TYPE invoice_payment_status AS ENUM ('UNPAID', 'PARTIALLY_PAID', 'PAID');

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT UNIQUE NOT NULL,
  order_id BIGINT REFERENCES orders(id) ON DELETE RESTRICT NOT NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  invoice_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  due_date TIMESTAMPTZ NOT NULL,
  subtotal NUMERIC(12, 2) NOT NULL,
  discount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  tax NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(12, 2) NOT NULL,
  amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  remaining_balance NUMERIC(12, 2) NOT NULL,
  payment_status invoice_payment_status NOT NULL DEFAULT 'UNPAID',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  discount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  total NUMERIC(12, 2) NOT NULL
);

-- 7. PURCHASES & ITEMS
CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_number TEXT UNIQUE NOT NULL,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE RESTRICT NOT NULL,
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  total_amount NUMERIC(12, 2) NOT NULL,
  amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  payment_status invoice_payment_status NOT NULL DEFAULT 'UNPAID',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS purchase_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id BIGINT REFERENCES purchases(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  purchase_price NUMERIC(10, 2) NOT NULL,
  total NUMERIC(12, 2) NOT NULL
);

-- 8. PAYMENTS
CREATE TYPE payment_type AS ENUM ('RETAILER_COLLECTION', 'SUPPLIER_PAYMENT');
CREATE TYPE payment_method AS ENUM ('CASH', 'BANK_TRANSFER', 'CHEQUE', 'MOBILE_MONEY');

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_number TEXT UNIQUE NOT NULL,
  type payment_type NOT NULL,
  entity_id BIGINT NOT NULL, -- retailer_id or supplier_id
  entity_name TEXT NOT NULL,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
  purchase_id BIGINT REFERENCES purchases(id) ON DELETE SET NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  payment_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  payment_method payment_method NOT NULL DEFAULT 'CASH',
  reference_number TEXT,
  notes TEXT,
  recorded_by_user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 9. AUDITABLE INVENTORY MOVEMENTS
CREATE TYPE movement_type AS ENUM (
  'PURCHASE_RECEIPT',
  'ORDER_DELIVERY',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT'
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  movement_type movement_type NOT NULL,
  quantity INT NOT NULL,
  previous_stock INT NOT NULL,
  new_stock INT NOT NULL,
  reference_type TEXT NOT NULL, -- 'ORDER', 'PURCHASE', 'MANUAL_ADJUSTMENT'
  reference_id BIGINT,
  reference_number TEXT,
  reason_or_notes TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 10. DELIVERIES
CREATE TYPE delivery_status AS ENUM ('SCHEDULED', 'DISPATCHED', 'DELIVERED', 'FAILED');

CREATE TABLE IF NOT EXISTS deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  delivery_address TEXT NOT NULL,
  driver_name TEXT,
  driver_phone TEXT,
  status delivery_status NOT NULL DEFAULT 'SCHEDULED',
  scheduled_date TIMESTAMPTZ NOT NULL,
  delivered_date TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE retailers ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;

-- Helper function to check if current user is OWNER
CREATE OR REPLACE FUNCTION is_owner()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'OWNER'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles: Authenticated users can view profiles; users can insert/update their own; owners can manage all
CREATE POLICY "Users can read profiles" ON profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert profiles" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id OR is_owner() OR NOT EXISTS (SELECT 1 FROM profiles));
CREATE POLICY "Users can update profiles" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id OR is_owner());
CREATE POLICY "Owners can delete profiles" ON profiles FOR DELETE TO authenticated USING (is_owner());

-- Products: Everyone authenticated can view; product modifications are owner-controlled
CREATE POLICY "Read products" ON products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Manage products" ON products FOR ALL TO authenticated USING (is_owner());

-- Categories
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read categories" ON categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Manage categories" ON categories FOR ALL TO authenticated USING (is_owner());

-- Suppliers: Owner-controlled
CREATE POLICY "Read suppliers" ON suppliers FOR SELECT TO authenticated USING (is_owner());
CREATE POLICY "Manage suppliers" ON suppliers FOR ALL TO authenticated USING (is_owner());

-- Retailers: Salespersons can access their assigned retailers; modifications are owner-controlled
CREATE POLICY "Retailers select policy" ON retailers FOR SELECT TO authenticated USING (
  is_owner() OR assigned_salesperson_id = auth.uid()
);
CREATE POLICY "Retailers manage policy" ON retailers FOR ALL TO authenticated USING (is_owner());

-- Orders: Salespersons can see their own orders; owners can access all orders; salespersons can create for themselves
CREATE POLICY "Orders select policy" ON orders FOR SELECT TO authenticated USING (
  is_owner() OR salesperson_id = auth.uid()
);
CREATE POLICY "Salespersons can create orders" ON orders FOR INSERT TO authenticated WITH CHECK (
  salesperson_id = auth.uid() OR is_owner()
);
CREATE POLICY "Only owners can approve orders" ON orders FOR UPDATE TO authenticated USING (
  is_owner() OR (salesperson_id = auth.uid() AND status IN ('DRAFT', 'CHANGES_REQUESTED'))
);
CREATE POLICY "Owners can delete orders" ON orders FOR DELETE TO authenticated USING (is_owner());

-- Order items: Authenticated users can SELECT, INSERT, UPDATE
CREATE POLICY "Order items select policy" ON order_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Order items insert policy" ON order_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Order items update policy" ON order_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Order items delete policy" ON order_items FOR DELETE TO authenticated USING (is_owner());

-- Invoices: Authenticated users can SELECT, INSERT, UPDATE
CREATE POLICY "Invoices select policy" ON invoices FOR SELECT TO authenticated USING (true);
CREATE POLICY "Invoices insert policy" ON invoices FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Invoices update policy" ON invoices FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Invoices delete policy" ON invoices FOR DELETE TO authenticated USING (is_owner());

-- Invoice items: Authenticated users can SELECT, INSERT, UPDATE
CREATE POLICY "Invoice items select policy" ON invoice_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Invoice items insert policy" ON invoice_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Invoice items update policy" ON invoice_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Invoice items delete policy" ON invoice_items FOR DELETE TO authenticated USING (is_owner());

-- Purchases: Owner-controlled
CREATE POLICY "Purchases select policy" ON purchases FOR SELECT TO authenticated USING (is_owner());
CREATE POLICY "Purchases manage policy" ON purchases FOR ALL TO authenticated USING (is_owner());

-- Purchase items: Owner-controlled
CREATE POLICY "Purchase items select policy" ON purchase_items FOR SELECT TO authenticated USING (is_owner());
CREATE POLICY "Purchase items manage policy" ON purchase_items FOR ALL TO authenticated USING (is_owner());

-- Payments: Authenticated users can INSERT and SELECT payments
CREATE POLICY "Payments select policy" ON payments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Payments insert policy" ON payments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Payments update policy" ON payments FOR UPDATE TO authenticated USING (is_owner());
CREATE POLICY "Payments delete policy" ON payments FOR DELETE TO authenticated USING (is_owner());

-- Inventory movements
CREATE POLICY "Movements select policy" ON inventory_movements FOR SELECT TO authenticated USING (true);
CREATE POLICY "Movements insert policy" ON inventory_movements FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Movements delete policy" ON inventory_movements FOR DELETE TO authenticated USING (is_owner());

-- Deliveries: Authenticated users can SELECT, INSERT, UPDATE
CREATE POLICY "Deliveries select policy" ON deliveries FOR SELECT TO authenticated USING (true);
CREATE POLICY "Deliveries insert policy" ON deliveries FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Deliveries update policy" ON deliveries FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Deliveries delete policy" ON deliveries FOR DELETE TO authenticated USING (is_owner());

-- Helper RPC for atomic retailer balance updates
CREATE OR REPLACE FUNCTION increment_retailer_balance(retailer_id BIGINT, delta NUMERIC)
RETURNS VOID AS $$
BEGIN
  UPDATE retailers
  SET outstanding_balance = outstanding_balance + delta
  WHERE id = retailer_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper RPC for atomic supplier balance updates
CREATE OR REPLACE FUNCTION increment_supplier_balance(p_supplier_id BIGINT, delta NUMERIC)
RETURNS VOID AS $$
BEGIN
  UPDATE suppliers
  SET payable_balance = payable_balance + delta
  WHERE id = p_supplier_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 11. COMPANY / BUSINESS PROFILE (SINGLETON CONFIGURATION)
CREATE TABLE IF NOT EXISTS company_profile (
  id BIGINT PRIMARY KEY DEFAULT 1,
  company_name TEXT NOT NULL DEFAULT 'DistriFlow ERP',
  legal_name TEXT,
  business_type TEXT DEFAULT 'Wholesale & FMCG Distribution',
  tagline TEXT DEFAULT 'Distribution Management & Wholesale Supply',
  phone TEXT DEFAULT '+977-1-4500000',
  alternate_phone TEXT,
  email TEXT DEFAULT 'info@distriflow.internal',
  website TEXT,
  address TEXT DEFAULT 'Kathmandu, Nepal',
  city TEXT DEFAULT 'Kathmandu',
  district TEXT DEFAULT 'Kathmandu',
  province TEXT DEFAULT 'Bagmati Province',
  country TEXT DEFAULT 'Nepal',
  pan_number TEXT,
  vat_number TEXT,
  registration_number TEXT,
  logo_url TEXT,
  invoice_header_logo_url TEXT,
  invoice_footer_text TEXT DEFAULT 'Thank you for your business. Cheques payable to company account.',
  receipt_footer_text TEXT DEFAULT 'Official acknowledgment of payment received.',
  default_invoice_notes TEXT DEFAULT 'Goods once sold and delivered in good order are subject to distributor return policy within 7 working days.',
  default_payment_terms TEXT DEFAULT 'Net 30 Days',
  currency TEXT DEFAULT 'NPR',
  currency_symbol TEXT DEFAULT 'Rs.',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE company_profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read company profile" ON company_profile FOR SELECT TO authenticated USING (true);
CREATE POLICY "Owners manage company profile" ON company_profile FOR ALL TO authenticated USING (is_owner());

-- Ensure singleton default row exists
INSERT INTO company_profile (id, company_name, legal_name, phone, email, address, city, country)
VALUES (1, 'DistriFlow ERP', 'DistriFlow Distribution Solutions Pvt. Ltd.', '+977-1-4500000', 'info@distriflow.internal', 'Kathmandu, Nepal', 'Kathmandu', 'Nepal')
ON CONFLICT (id) DO NOTHING;

-- 12. AUDIT LOGS (IMMUTABLE BUSINESS TRAIL)
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  user_role TEXT NOT NULL DEFAULT 'OWNER',
  action TEXT NOT NULL,
  module TEXT NOT NULL,
  record_id TEXT NOT NULL,
  record_identifier TEXT,
  description TEXT NOT NULL,
  reason TEXT,
  metadata JSONB,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owners can view audit logs" ON audit_logs FOR SELECT TO authenticated USING (is_owner());
CREATE POLICY "System and users can insert audit logs" ON audit_logs FOR INSERT TO authenticated WITH CHECK (true);
-- Notice: NO UPDATE or DELETE policies on audit_logs! It is strictly append-only and protected from normal deletion.

-- Add lifecycle columns to existing tables if missing
DO $$
BEGIN
  -- Payments status
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='payments' AND column_name='status') THEN
    ALTER TABLE payments ADD COLUMN status TEXT NOT NULL DEFAULT 'ACTIVE';
    ALTER TABLE payments ADD COLUMN reversed_at TIMESTAMPTZ;
    ALTER TABLE payments ADD COLUMN reversed_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
    ALTER TABLE payments ADD COLUMN reversal_reason TEXT;
  END IF;

  -- Invoices status / void
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='invoices' AND column_name='status') THEN
    ALTER TABLE invoices ADD COLUMN status TEXT NOT NULL DEFAULT 'POSTED';
    ALTER TABLE invoices ADD COLUMN voided_at TIMESTAMPTZ;
    ALTER TABLE invoices ADD COLUMN voided_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
    ALTER TABLE invoices ADD COLUMN void_reason TEXT;
  END IF;

  -- Purchases status / void
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='purchases' AND column_name='status') THEN
    ALTER TABLE purchases ADD COLUMN status TEXT NOT NULL DEFAULT 'POSTED';
    ALTER TABLE purchases ADD COLUMN voided_at TIMESTAMPTZ;
    ALTER TABLE purchases ADD COLUMN voided_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
    ALTER TABLE purchases ADD COLUMN void_reason TEXT;
  END IF;

  -- Orders soft delete / archive
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='is_archived') THEN
    ALTER TABLE orders ADD COLUMN is_archived BOOLEAN NOT NULL DEFAULT false;
    ALTER TABLE orders ADD COLUMN archived_at TIMESTAMPTZ;
  END IF;

  -- Products archive metadata
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='products' AND column_name='archived_at') THEN
    ALTER TABLE products ADD COLUMN archived_at TIMESTAMPTZ;
    ALTER TABLE products ADD COLUMN archived_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
  END IF;

  -- Retailers archive metadata
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='retailers' AND column_name='archived_at') THEN
    ALTER TABLE retailers ADD COLUMN archived_at TIMESTAMPTZ;
    ALTER TABLE retailers ADD COLUMN archived_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
  END IF;

  -- Suppliers archive metadata
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='suppliers' AND column_name='archived_at') THEN
    ALTER TABLE suppliers ADD COLUMN archived_at TIMESTAMPTZ;
    ALTER TABLE suppliers ADD COLUMN archived_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
  END IF;

  -- Profiles archive metadata
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='archived_at') THEN
    ALTER TABLE profiles ADD COLUMN archived_at TIMESTAMPTZ;
    ALTER TABLE profiles ADD COLUMN archived_by UUID REFERENCES profiles(id) ON DELETE SET NULL;
  END IF;
END $$;

