-- ==============================================================================
-- DistriFlow ERP — Supabase PostgreSQL Schema & Row Level Security (RLS) Policies
-- ==============================================================================

-- 1. PROFILES & ROLES
CREATE TYPE user_role AS ENUM ('OWNER', 'SALESPERSON');

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'SALESPERSON',
  phone TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. SUPPLIERS
CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT,
  payable_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 3. PRODUCT CATEGORIES & PRODUCTS
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'pcs',
  purchase_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  selling_price NUMERIC(10, 2) NOT NULL,
  current_stock INT NOT NULL DEFAULT 0,
  min_stock_level INT NOT NULL DEFAULT 10,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 4. RETAILERS / CUSTOMERS
CREATE TABLE IF NOT EXISTS retailers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  address TEXT NOT NULL,
  city TEXT,
  assigned_salesperson_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  credit_limit NUMERIC(12, 2) NOT NULL DEFAULT 5000.00,
  outstanding_balance NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 5. ORDERS & ITEMS
CREATE TYPE order_status AS ENUM (
  'DRAFT',
  'SUBMITTED',
  'CHANGES_REQUESTED',
  'APPROVED',
  'REJECTED',
  'INVOICED',
  'DISPATCHED',
  'DELIVERED',
  'CANCELLED'
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT UNIQUE NOT NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  salesperson_id UUID REFERENCES profiles(id) ON DELETE RESTRICT NOT NULL,
  order_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  status order_status NOT NULL DEFAULT 'DRAFT',
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  discount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  notes TEXT,
  owner_feedback TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10, 2) NOT NULL,
  discount_percent NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
  total NUMERIC(12, 2) NOT NULL
);

-- 6. INVOICES & ITEMS
CREATE TYPE invoice_payment_status AS ENUM ('UNPAID', 'PARTIALLY_PAID', 'PAID');

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number TEXT UNIQUE NOT NULL,
  order_id BIGINT REFERENCES orders(id) ON DELETE RESTRICT NOT NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  invoice_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  due_date TIMESTAMPTZ NOT NULL,
  subtotal NUMERIC(12, 2) NOT NULL,
  discount NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  tax NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  total_amount NUMERIC(12, 2) NOT NULL,
  amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  remaining_balance NUMERIC(12, 2) NOT NULL,
  payment_status invoice_payment_status NOT NULL DEFAULT 'UNPAID',
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL,
  unit_price NUMERIC(10, 2) NOT NULL,
  discount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  total NUMERIC(12, 2) NOT NULL
);

-- 7. PURCHASES & ITEMS
CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_number TEXT UNIQUE NOT NULL,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE RESTRICT NOT NULL,
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  total_amount NUMERIC(12, 2) NOT NULL,
  amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
  payment_status invoice_payment_status NOT NULL DEFAULT 'UNPAID',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS purchase_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id BIGINT REFERENCES purchases(id) ON DELETE CASCADE NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  quantity INT NOT NULL CHECK (quantity > 0),
  purchase_price NUMERIC(10, 2) NOT NULL,
  total NUMERIC(12, 2) NOT NULL
);

-- 8. PAYMENTS
CREATE TYPE payment_type AS ENUM ('RETAILER_COLLECTION', 'SUPPLIER_PAYMENT');
CREATE TYPE payment_method AS ENUM ('CASH', 'BANK_TRANSFER', 'CHEQUE', 'MOBILE_MONEY');

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_number TEXT UNIQUE NOT NULL,
  type payment_type NOT NULL,
  entity_id BIGINT NOT NULL, -- retailer_id or supplier_id
  entity_name TEXT NOT NULL,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
  purchase_id BIGINT REFERENCES purchases(id) ON DELETE SET NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
  payment_date TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  payment_method payment_method NOT NULL DEFAULT 'CASH',
  reference_number TEXT,
  notes TEXT,
  recorded_by_user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 9. AUDITABLE INVENTORY MOVEMENTS
CREATE TYPE movement_type AS ENUM (
  'PURCHASE_RECEIPT',
  'ORDER_DELIVERY',
  'ADJUSTMENT_IN',
  'ADJUSTMENT_OUT'
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT NOT NULL,
  movement_type movement_type NOT NULL,
  quantity INT NOT NULL,
  previous_stock INT NOT NULL,
  new_stock INT NOT NULL,
  reference_type TEXT NOT NULL, -- 'ORDER', 'PURCHASE', 'MANUAL_ADJUSTMENT'
  reference_id BIGINT,
  reference_number TEXT,
  reason_or_notes TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 10. DELIVERIES
CREATE TYPE delivery_status AS ENUM ('SCHEDULED', 'DISPATCHED', 'DELIVERED', 'FAILED');

CREATE TABLE IF NOT EXISTS deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  invoice_id BIGINT REFERENCES invoices(id) ON DELETE SET NULL,
  retailer_id BIGINT REFERENCES retailers(id) ON DELETE RESTRICT NOT NULL,
  delivery_address TEXT NOT NULL,
  driver_name TEXT,
  driver_phone TEXT,
  status delivery_status NOT NULL DEFAULT 'SCHEDULED',
  scheduled_date TIMESTAMPTZ NOT NULL,
  delivered_date TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE retailers ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;

-- Helper function to check if current user is OWNER
CREATE OR REPLACE FUNCTION is_owner()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'OWNER'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles: Authenticated users can view profiles; users can insert/update their own; owners can manage all
CREATE POLICY "Users can read profiles" ON profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert profiles" ON profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id OR is_owner() OR NOT EXISTS (SELECT 1 FROM profiles));
CREATE POLICY "Users can update profiles" ON profiles FOR UPDATE TO authenticated USING (auth.uid() = id OR is_owner());
CREATE POLICY "Owners can delete profiles" ON profiles FOR DELETE TO authenticated USING (is_owner());

-- Products: Everyone authenticated can view; owners can manage
CREATE POLICY "Read products" ON products FOR SELECT TO authenticated USING (true);
CREATE POLICY "Manage products" ON products FOR ALL TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Categories
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read categories" ON categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "Manage categories" ON categories FOR ALL TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Suppliers: Authenticated can view; owners can manage
CREATE POLICY "Read suppliers" ON suppliers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Manage suppliers" ON suppliers FOR ALL TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Retailers: Owners can manage all; Salespersons can view and update
CREATE POLICY "Retailers select policy" ON retailers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Retailers insert policy" ON retailers FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Retailers update policy" ON retailers FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Retailers delete policy" ON retailers FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Orders: Salespersons can insert/read; Owners can manage all
CREATE POLICY "Orders select policy" ON orders FOR SELECT TO authenticated USING (true);
CREATE POLICY "Orders insert policy" ON orders FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Orders update policy" ON orders FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Orders delete policy" ON orders FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Order items
CREATE POLICY "Order items select policy" ON order_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Order items insert policy" ON order_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Order items update policy" ON order_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Order items delete policy" ON order_items FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Invoices & Items
CREATE POLICY "Invoices select policy" ON invoices FOR SELECT TO authenticated USING (true);
CREATE POLICY "Invoices insert policy" ON invoices FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Invoices update policy" ON invoices FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Invoices delete policy" ON invoices FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

CREATE POLICY "Invoice items select policy" ON invoice_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Invoice items insert policy" ON invoice_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Invoice items update policy" ON invoice_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Invoice items delete policy" ON invoice_items FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Purchases & Items
CREATE POLICY "Purchases select policy" ON purchases FOR SELECT TO authenticated USING (true);
CREATE POLICY "Purchases insert policy" ON purchases FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Purchases update policy" ON purchases FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Purchases delete policy" ON purchases FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

CREATE POLICY "Purchase items select policy" ON purchase_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "Purchase items insert policy" ON purchase_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Purchase items update policy" ON purchase_items FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Purchase items delete policy" ON purchase_items FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Payments
CREATE POLICY "Payments select policy" ON payments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Payments insert policy" ON payments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Payments update policy" ON payments FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Payments delete policy" ON payments FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Inventory movements
CREATE POLICY "Movements select policy" ON inventory_movements FOR SELECT TO authenticated USING (true);
CREATE POLICY "Movements insert policy" ON inventory_movements FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Movements delete policy" ON inventory_movements FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Deliveries
CREATE POLICY "Deliveries select policy" ON deliveries FOR SELECT TO authenticated USING (true);
CREATE POLICY "Deliveries insert policy" ON deliveries FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Deliveries update policy" ON deliveries FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Deliveries delete policy" ON deliveries FOR DELETE TO authenticated USING (is_owner() OR NOT EXISTS (SELECT 1 FROM profiles WHERE role = 'OWNER'));

-- Helper RPC for atomic retailer balance updates
CREATE OR REPLACE FUNCTION increment_retailer_balance(retailer_id BIGINT, delta NUMERIC)
RETURNS VOID AS $$
BEGIN
  UPDATE retailers
  SET outstanding_balance = outstanding_balance + delta
  WHERE id = retailer_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
