import {
  User,
  Retailer,
  Supplier,
  Product,
  Order,
  OrderItem,
  Invoice,
  Delivery,
  Payment,
  InventoryMovement,
} from '../types/erp';

const now = Date.now();
const dayMs = 24 * 60 * 60 * 1000;

/**
 * ISOLATED DEVELOPMENT SEED DATA
 *
 * CAUTION: These are evaluation prototype records.
 * They are NEVER to be treated as real production company records.
 * When Supabase is connected, live PostgreSQL records are fetched via RLS.
 */

export const INITIAL_DEMO_USERS: User[] = [
  {
    id: 1,
    username: 'admin',
    fullName: 'Sarah Jenkins',
    role: 'OWNER',
    email: 'admin@distriflow-demo.com',
    phone: '+1 (555) 234-5678',
    isActive: true,
    createdAt: now - 60 * dayMs,
  },
  {
    id: 2,
    username: 'john',
    fullName: 'John Davis',
    role: 'SALESPERSON',
    email: 'john.rep@distriflow-demo.com',
    phone: '+1 (555) 345-6789',
    isActive: true,
    createdAt: now - 45 * dayMs,
  },
  {
    id: 3,
    username: 'maria',
    fullName: 'Maria Santos',
    role: 'SALESPERSON',
    email: 'maria.rep@distriflow-demo.com',
    phone: '+1 (555) 456-7890',
    isActive: true,
    createdAt: now - 30 * dayMs,
  },
];

export const INITIAL_DEMO_SUPPLIERS: Supplier[] = [
  {
    id: 1,
    name: 'Apex Beverage Distributors',
    contactPerson: 'Michael Chang',
    phone: '+1 (555) 111-2233',
    email: 'orders@apexbeverage.com',
    address: '1200 Industrial Pkwy, Sector 4',
    payableBalance: 4250.0,
    isActive: true,
    createdAt: now - 60 * dayMs,
  },
  {
    id: 2,
    name: 'Prime Foods Wholesale',
    contactPerson: 'Elena Rostova',
    phone: '+1 (555) 222-3344',
    email: 'supply@primefoods.com',
    address: '45 Harbor Blvd, Pier 9',
    payableBalance: 6800.0,
    isActive: true,
    createdAt: now - 60 * dayMs,
  },
  {
    id: 3,
    name: 'CleanCare Household Supplies',
    contactPerson: 'David Miller',
    phone: '+1 (555) 333-4455',
    email: 'sales@cleancare.com',
    address: '88 Logistic Way, Suite 100',
    payableBalance: 1500.0,
    isActive: true,
    createdAt: now - 60 * dayMs,
  },
];

export const INITIAL_DEMO_PRODUCTS: Product[] = [
  {
    id: 1,
    sku: 'BEV-001',
    name: 'Premium Arabica Iced Coffee (12pk)',
    category: 'Beverages',
    unit: 'case',
    purchasePrice: 18.5,
    sellingPrice: 27.5,
    currentStock: 120,
    minStockLevel: 30,
    supplierId: 1,
    supplierName: 'Apex Beverage Distributors',
    isActive: true,
    createdAt: now - 50 * dayMs,
  },
  {
    id: 2,
    sku: 'BEV-002',
    name: 'Sparkling Spring Water 500ml (24pk)',
    category: 'Beverages',
    unit: 'case',
    purchasePrice: 11.0,
    sellingPrice: 17.5,
    currentStock: 85,
    minStockLevel: 25,
    supplierId: 1,
    supplierName: 'Apex Beverage Distributors',
    isActive: true,
    createdAt: now - 50 * dayMs,
  },
  {
    id: 3,
    sku: 'SNK-001',
    name: 'Organic Sea Salt Chips (30pk)',
    category: 'Snacks',
    unit: 'box',
    purchasePrice: 22.0,
    sellingPrice: 34.0,
    currentStock: 8, // Low Stock
    minStockLevel: 20,
    supplierId: 2,
    supplierName: 'Prime Foods Wholesale',
    isActive: true,
    createdAt: now - 50 * dayMs,
  },
  {
    id: 4,
    sku: 'SNK-002',
    name: 'Almond Protein Crunch Bars (24pk)',
    category: 'Snacks',
    unit: 'box',
    purchasePrice: 26.0,
    sellingPrice: 42.0,
    currentStock: 65,
    minStockLevel: 15,
    supplierId: 2,
    supplierName: 'Prime Foods Wholesale',
    isActive: true,
    createdAt: now - 50 * dayMs,
  },
  {
    id: 5,
    sku: 'CLN-001',
    name: 'Commercial Surface Sanitizer 5L',
    category: 'Household',
    unit: 'jug',
    purchasePrice: 14.2,
    sellingPrice: 24.0,
    currentStock: 5, // Low Stock
    minStockLevel: 15,
    supplierId: 3,
    supplierName: 'CleanCare Household Supplies',
    isActive: true,
    createdAt: now - 50 * dayMs,
  },
  {
    id: 6,
    sku: 'GRC-001',
    name: 'Golden Grain Wheat Flour 25kg',
    category: 'Groceries',
    unit: 'bag',
    purchasePrice: 28.0,
    sellingPrice: 38.5,
    currentStock: 90,
    minStockLevel: 20,
    supplierId: 2,
    supplierName: 'Prime Foods Wholesale',
    isActive: true,
    createdAt: now - 50 * dayMs,
  },
];

export const INITIAL_DEMO_RETAILERS: Retailer[] = [
  {
    id: 1,
    name: 'Metro Central Mart',
    contactPerson: 'Arthur Pendelton',
    phone: '+1 (555) 777-8899',
    email: 'arthur@metromart.com',
    address: '450 Commercial Ave',
    city: 'Metropolis',
    assignedSalespersonId: 2, // John Davis
    creditLimit: 8000.0,
    outstandingBalance: 1650.0,
    isActive: true,
    createdAt: now - 40 * dayMs,
  },
  {
    id: 2,
    name: 'Sunrise Convenience Store',
    contactPerson: 'Lucy Henderson',
    phone: '+1 (555) 888-9900',
    email: 'lucy@sunrisestore.com',
    address: '12 4th Street',
    city: 'Westside',
    assignedSalespersonId: 2, // John Davis
    creditLimit: 4000.0,
    outstandingBalance: 840.0,
    isActive: true,
    createdAt: now - 40 * dayMs,
  },
  {
    id: 3,
    name: 'Valley Grocers Co-op',
    contactPerson: 'Gregory Vance',
    phone: '+1 (555) 999-0011',
    email: 'greg@valleycoop.com',
    address: '89 Valley View Rd',
    city: 'Oakdale',
    assignedSalespersonId: 3, // Maria Santos
    creditLimit: 12000.0,
    outstandingBalance: 3200.0,
    isActive: true,
    createdAt: now - 30 * dayMs,
  },
  {
    id: 4,
    name: 'Corner Pocket Bodega',
    contactPerson: 'Marcus Cole',
    phone: '+1 (555) 321-6547',
    email: 'marcus@pocketbodega.com',
    address: '707 Elm St',
    city: 'Downtown',
    assignedSalespersonId: 3, // Maria Santos
    creditLimit: 3000.0,
    outstandingBalance: 0.0,
    isActive: true,
    createdAt: now - 20 * dayMs,
  },
];

export const INITIAL_DEMO_ORDERS: Order[] = [
  {
    id: 1,
    orderNumber: 'ORD-2026-001',
    retailerId: 1,
    retailerName: 'Metro Central Mart',
    salespersonId: 2,
    salespersonName: 'John Davis',
    orderDate: now - 2 * 60 * 60 * 1000,
    status: 'SUBMITTED',
    subtotal: 735.0,
    discount: 25.0,
    totalAmount: 710.0,
    notes: 'Urgent weekend replenishment. Store requested morning delivery.',
    ownerFeedback: '',
    createdAt: now - 2 * 60 * 60 * 1000,
    updatedAt: now - 2 * 60 * 60 * 1000,
  },
  {
    id: 2,
    orderNumber: 'ORD-2026-002',
    retailerId: 2,
    retailerName: 'Sunrise Convenience Store',
    salespersonId: 2,
    salespersonName: 'John Davis',
    orderDate: now - 1 * dayMs,
    status: 'CHANGES_REQUESTED',
    subtotal: 544.0,
    discount: 50.0,
    totalAmount: 494.0,
    notes: 'Regular store replenishment.',
    ownerFeedback: 'Please adjust discount to max 5% or verify credit approval before resubmitting.',
    createdAt: now - 1 * dayMs,
    updatedAt: now - 20 * 60 * 60 * 1000,
  },
  {
    id: 3,
    orderNumber: 'ORD-2026-003',
    retailerId: 3,
    retailerName: 'Valley Grocers Co-op',
    salespersonId: 3,
    salespersonName: 'Maria Santos',
    orderDate: now - 2 * dayMs,
    status: 'APPROVED',
    subtotal: 1155.0,
    discount: 0.0,
    totalAmount: 1155.0,
    notes: 'Pre-approved weekly bulk run.',
    ownerFeedback: 'Approved by Sarah J. Pack for distribution.',
    createdAt: now - 2 * dayMs,
    updatedAt: now - 36 * 60 * 60 * 1000,
  },
  {
    id: 4,
    orderNumber: 'ORD-2026-004',
    retailerId: 1,
    retailerName: 'Metro Central Mart',
    salespersonId: 2,
    salespersonName: 'John Davis',
    orderDate: now - 5 * dayMs,
    status: 'DELIVERED',
    subtotal: 1650.0,
    discount: 0.0,
    totalAmount: 1650.0,
    notes: 'Delivered without issues.',
    ownerFeedback: 'Completed.',
    createdAt: now - 5 * dayMs,
    updatedAt: now - 4 * dayMs,
  },
];

export const INITIAL_DEMO_ORDER_ITEMS: OrderItem[] = [
  {
    id: 1,
    orderId: 1,
    productId: 1,
    productName: 'Premium Arabica Iced Coffee (12pk)',
    productSku: 'BEV-001',
    quantity: 15,
    unitPrice: 27.5,
    discountPercent: 0,
    total: 412.5,
  },
  {
    id: 2,
    orderId: 1,
    productId: 2,
    productName: 'Sparkling Spring Water 500ml (24pk)',
    productSku: 'BEV-002',
    quantity: 20,
    unitPrice: 17.5,
    discountPercent: 0,
    total: 350.0,
  },
  {
    id: 3,
    orderId: 2,
    productId: 3,
    productName: 'Organic Sea Salt Chips (30pk)',
    productSku: 'SNK-001',
    quantity: 16,
    unitPrice: 34.0,
    discountPercent: 0,
    total: 544.0,
  },
  {
    id: 4,
    orderId: 3,
    productId: 6,
    productName: 'Golden Grain Wheat Flour 25kg',
    productSku: 'GRC-001',
    quantity: 30,
    unitPrice: 38.5,
    discountPercent: 0,
    total: 1155.0,
  },
];

export const INITIAL_DEMO_INVOICES: Invoice[] = [
  {
    id: 1,
    invoiceNumber: 'INV-2026-101',
    orderId: 4,
    retailerId: 1,
    retailerName: 'Metro Central Mart',
    invoiceDate: now - 5 * dayMs,
    dueDate: now + 25 * dayMs,
    subtotal: 1650.0,
    discount: 0.0,
    tax: 0.0,
    totalAmount: 1650.0,
    amountPaid: 650.0,
    remainingBalance: 1000.0,
    paymentStatus: 'PARTIALLY_PAID',
    createdAt: now - 5 * dayMs,
  },
];

export const INITIAL_DEMO_DELIVERIES: Delivery[] = [
  {
    id: 1,
    orderId: 4,
    orderNumber: 'ORD-2026-004',
    invoiceId: 1,
    invoiceNumber: 'INV-2026-101',
    retailerId: 1,
    retailerName: 'Metro Central Mart',
    deliveryAddress: '450 Commercial Ave, Metropolis',
    driverName: 'Carlos Gomez',
    driverPhone: '+1 (555) 444-1234',
    status: 'DELIVERED',
    scheduledDate: now - 5 * dayMs,
    deliveredDate: now - 4 * dayMs,
    notes: 'Signed and received by receiving dock supervisor.',
    createdAt: now - 5 * dayMs,
  },
];

export const INITIAL_DEMO_PAYMENTS: Payment[] = [
  {
    id: 1,
    paymentNumber: 'PAY-2026-001',
    type: 'RETAILER_COLLECTION',
    entityId: 1,
    entityName: 'Metro Central Mart',
    invoiceId: 1,
    amount: 650.0,
    paymentDate: now - 3 * dayMs,
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'WIRE-8930412',
    notes: 'First installment for INV-2026-101',
    recordedByUserId: 2,
    recordedByName: 'John Davis',
    createdAt: now - 3 * dayMs,
  },
];

export const INITIAL_DEMO_MOVEMENTS: InventoryMovement[] = [
  {
    id: 1,
    productId: 1,
    productName: 'Premium Arabica Iced Coffee (12pk)',
    movementType: 'PURCHASE_RECEIPT',
    quantity: 100,
    previousStock: 20,
    newStock: 120,
    referenceType: 'PURCHASE',
    referenceId: 1,
    referenceNumber: 'PUR-2026-01',
    reasonOrNotes: 'Received supplier delivery from Apex Beverage Distributors',
    timestamp: now - 7 * dayMs,
  },
  {
    id: 2,
    productId: 3,
    productName: 'Organic Sea Salt Chips (30pk)',
    movementType: 'ORDER_DELIVERY',
    quantity: -20,
    previousStock: 28,
    newStock: 8,
    referenceType: 'ORDER',
    referenceId: 4,
    referenceNumber: 'ORD-2026-004',
    reasonOrNotes: 'Dispatched and delivered to Metro Central Mart',
    timestamp: now - 4 * dayMs,
  },
];
